### ISSUE TITLE
Does this repo still work?

### ISSUE THREAD

**Issue by kevinlinxc** [ShineAsNine/GfycatDownloader#2]
I created a text file with:

```
https://gfycat.com/enchantingminiaturechital
```

and tried to run the exe in 9 mode. I get an getaddrinfo failed error:
```
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 363, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CAA6F64F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='giant.gfycat.com', port=443): Max retries exceeded with url: /EnchantingMiniatureChital.mp4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CAA6F64F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "utils\download_gfys.py", line 72, in start_download
  File "utils\download_gfys.py", line 182, in download_gfy
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='giant.gfycat.com', port=443): Max retries exceeded with url: /EnchantingMiniatureChital.mp4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CAA6F64F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

This makes sense because I can't access the link at all through the browser, and it seems like the Python script is trying to access site too?

**Comment by ShineAsNine** [comment]
Nope gfycat is dead, doesn't work anymore
